version: '3.9'

services:
  php:
    build: .
    container_name: php_app
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chipstore
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./src/dal/db/chipstore.sql:/docker-entrypoint-initdb.d/chipstore.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
